FROM maven:3.9.9-eclipse-temurin-17 AS builder

WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn --no-transfer-progress clean package -DskipTests

FROM eclipse-temurin:17-jre-jammy

WORKDIR /app
COPY --from=builder /app/target/payments-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 9087
ENTRYPOINT ["java", "-jar", "app.jar"]
