spring:
  application:
    name: payments-service
  jackson:
    property-naming-strategy: SNAKE_CASE

payments:
  provider:
    stub:
      mode: SUCCESS

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
        liveness:
          include: livenessState,ping
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: payments-service

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{correlationId:-N/A}] %-5level %logger{36} - %msg%n"
