spring:
  application:
    name: payments-service
  jackson:
    property-naming-strategy: SNAKE_CASE

payments:
  provider:
    stub:
      mode: SUCCESS

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: payments-service
